plexwrangler/urls.py
from django.contrib import admin
from django.urls import path
from wrangler import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include

urlpatterns = [
    #   path('mediadirectory/<int:pk>/',
    #        views.MediaDirectoryDetailView.as_view(),
    #        name='media-directory-detail'),
    path('section/<int:pk>/',
         views.PlexSectionDetailView.as_view(),
         name='plex-section-detail'),
    path('movie/<int:pk>/',
         views.MovieUpdateView.as_view(),
         name='movie-update'),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('reports/pending-delete',
         views.pending_delete,
         name='report_pending_delete'),
    path('reports/pending-move',
         views.pending_move,
         name='report_pending_move'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('activity/', include('actstream.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wrangler/models.py
import requests
from io import BytesIO
from actstream import action
from django.db import models
import logging
from django.urls import reverse
from django.core import files
from django.contrib.auth.models import User

from django_currentuser.middleware import get_current_user


# Create your models here.
class PlexResource(models.Model):
    name = models.CharField(max_length=100, unique=True)

    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class PlexSection(models.Model):
    title = models.CharField(max_length=100)
    resource = models.ForeignKey(PlexResource, on_delete=models.CASCADE)
    media_type = models.CharField(max_length=100, null=True)
    hide_from_destinations = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_absolute_url(self):
        return reverse('plex-section-detail', args=[self.pk])

    def __str__(self):
        return f"{self.title} ({self.resource.name})"

    def __repr__(self):
        return f"{self.title} ({self.resource.name})"


class Movie(models.Model):
    name = models.CharField(max_length=200)
    container_directory = models.CharField(max_length=200,
                                           null=True,
                                           blank=True)
    year = models.IntegerField()
    guid = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    plex_section = models.ManyToManyField(PlexSection)
    desired_plex_section = models.ForeignKey(
        PlexSection,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        limit_choices_to={
            'media_type': 'movie',
            'hide_from_destinations': False
        },
        related_name='desired_plex_section')
    poster = models.ImageField(upload_to='images', blank=True, null=True)
    summary = models.TextField(blank=True)
    is_deleted = models.BooleanField(default=False)
    is_marked_for_delete = models.BooleanField(default=False)

    @property
    def get_absolute_url(self):
        return reverse('movie-update', args=[self.pk])

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user:
            a_user = user
        else:
            a_user = User.objects.get(username='admin')

        try:
            old = Movie.objects.get(pk=self.pk)
        except self.DoesNotExist:
            old = None
        if old:
            if old.is_marked_for_delete != self.is_marked_for_delete:
                if self.is_marked_for_delete:
                    verb = 'Set for deletion'
                else:
                    verb = 'UnSet for deletion'
                action.send(a_user, verb=verb, target=self)
            if old.desired_plex_section != self.desired_plex_section:
                action.send(a_user,
                            verb='Changed desired plex section for ',
                            action_object=self,
                            target=self.desired_plex_section)
        super().save(*args, **kwargs)
        if not old:
            action.send(a_user, verb="Created", target=self)

    def import_poster(self, poster_url):
        logging.warning("GUID: %s" % self.guid)

        # Get the filename from the url, used for saving later
        if self.guid.find("imdb://") != -1:
            file_name = "%s.jpg" % self.guid.split("imdb://")[1].split("?")[0]
            request = requests.get(poster_url, stream=True)
            try:
                request.raise_for_status()
                got_poster = True
            except:
                got_poster = False

            if got_poster:
                fp = BytesIO()
                fp.write(request.content)
                self.poster.save(file_name, files.File(fp))
        else:
            logging.warning("Could not find poster for %s" % self)

    def __str__(self):
        return f"{self.name} ({self.year})"

    def __repr__(self):
        return f"<Movie {self.guid}>"

    class Meta:
        ordering = ('created_at', )


# class Movie(models.Model):
#   name = models.CharField(max_length=100)
#   current_directory = models.ForeignKey(MediaDirectory,
#                                         on_delete=models.CASCADE,
#                                         related_name='current_movies')
#   desired_directory = models.ForeignKey(MediaDirectory,
#                                         on_delete=models.CASCADE,
#                                         blank=True,
#                                         null=True,
#                                         related_name='desired_movies')

#   is_deleted = models.BooleanField(default=False)
#   pending_deletion = models.BooleanField(default=False)

#   class Meta:
#       unique_together = ['name', 'current_directory']

#   def __str__(self):
#       return self.name

#   def __repr__(self):
#       return self.name

wrangler/views.py
# from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse
from actstream.models import any_stream
from .models import Movie, PlexSection
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


# Create your views here.
def index(request):
    template = loader.get_template('index.html')
    movies = Movie.objects.order_by('-created_at').filter(
        is_deleted=False)[0:12]
    context = {'recent_movies': movies}
    return HttpResponse(template.render(context, request))


def pending_delete(request):
    template = loader.get_template('pending_delete.html')
    movies = Movie.objects.filter(is_marked_for_delete=True, is_deleted=False)
    context = {'movies': movies}
    return HttpResponse(template.render(context, request))


def pending_move(request):
    template = loader.get_template('pending_move.html')
    movies = []
    for movie in Movie.objects.filter(
            is_marked_for_delete=False,
            is_deleted=False).exclude(desired_plex_section__isnull=True):
        if movie.desired_plex_section not in movie.plex_section.all():
            movies.append(movie)
    context = {'movies': movies}
    return HttpResponse(template.render(context, request))


class PlexSectionDetailView(DetailView):
    model = PlexSection


class MovieUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Movie

    success_message = 'Updated movie successfully!'
    fields = ['desired_plex_section', 'is_marked_for_delete']

    def get_success_url(self):
        # oview_name = 'update_movie'
        return self.request.POST.get('next')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stream'] = any_stream(self.get_object())
        return context

wrangler/templates/base.html
{% extends 'bootstrap.html' %}

{% load bootstrap4 %}


{% block bootstrap4_before_content %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Plex Media Wrangler</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Media Libraries</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          {% for section in plex_sections %}
            <a class="dropdown-item" href="{{ section.get_absolute_url }}">{{ section }}</a>
          {% endfor %}
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reports</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'report_pending_delete' %}">Pending Delete<a>
            <a class="dropdown-item" href="{% url 'report_pending_move' %}">Pending Move<a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Logout {{ user }}</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="/accounts/login">Login</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% endblock %}

{% block bootstrap4_content %}
<main role="main" class="container">
        <h1>{% block title %}Plex Media Wrangler{% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
        <br/>
        {% block content %}(no content){% endblock %}
</main>

{% endblock %}

wrangler/templates/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load static %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

{% block bootstrap4_extra_head %}
            <!-- <script type="text/javascript" src="/static/js/jquery.js" /> -->
                <link rel="stylesheet" href="{% static "jquery-ui/jquery-ui.min.css" %}" />
                <script src="{% static "jquery-ui/external/jquery/jquery.js" %}"></script>
                <script src="{% static "jquery-ui/jquery-ui.min.js" %}"></script>
{% endblock %}

wrangler/templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Recently Added Movies</p>

<div class="row">
    {% for movie in recent_movies %}
        <div class="col-xs-2">
            {% include 'movie/_mini.html' %}
        </div>
    {% endfor %}
</div>

{% endblock %}

wrangler/templates/movie/_mini.html
{% load thumbnail %}
{% thumbnail movie.poster 150x200 upscale as thumb %}
<a href="{{ movie.get_absolute_url }}">
<figure class="figure" width="200px">
  {% if movie.poster %}
      <img src="{{ thumb.url }}" class="figure-img img-fluid rounded" alt="{{ movie }}" title="{{ movie }}">
  {% endif %}
</figure>
</a>

wrangler/templates/pending_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load activity_tags %}

{% block content %}
<h2>Pending Deletion</h2>

<div class="row">
    {% for movie in movies %}
    <div class="col-sm">
        {% include 'movie/_mini.html' %}
    </div>
    {% endfor %}
</div>

{% endblock %}

wrangler/templates/pending_move.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load activity_tags %}

{% block content %}
<h2>Pending Move to Different Plex Section</h2>

<div class="row">
    {% for movie in movies %}
    <div class="col-sm">
        {% include 'movie/_mini.html' %}
    </div>
    {% endfor %}
</div>

{% endblock %}

wrangler/templates/wrangler/movie_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load activity_tags %}

{% block content %}
<h2>{{ object }}</h2>

<div class="row">
    <div class="col-sm">
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="hidden" name="next" value="{{ object.get_absolute_url }}">
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
    <div class="col-sm">
        {% for action in stream %}
        <div class="row">
            <div class="col-sm">
                {% display_action action %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

wrangler/templates/wrangler/plexsection_detail.html
{% extends 'base.html' %}

{% block content %}

<h3>{{ object }}</h3>

<div class="row">
    {% for movie in object.movie_set.all %}
        <div class="col-xs-2">
            {% include 'movie/_mini.html' %}
        </div>
    {% endfor %}
</div>


{% endblock %}